export const BrowserColors = {
	BgBlack: "background-color: black; color: white;",
	BgBlue: "background-color: blue; color: white;",
	BgCyan: "background-color: cyan; color: black;",
	BgGreen: "background-color: green; color: white;",
	BgMagenta: "background-color: magenta; color: white;",
	BgRed: "background-color: red; color: white;",
	BgWhite: "background-color: white; color: black;",
	BgYellow: "background-color: yellow; color: black;",
	Blink: "animation: blink 1s infinite;",
	Bright: "font-weight: bold;",
	Dim: "opacity: 0.6;",
	FgBlack: "color: black;",
	FgBlue: "color: blue;",
	FgCyan: "color: cyan;",
	FgGreen: "color: green;",
	FgMagenta: "color: magenta;",
	FgRed: "color: red;",
	FgWhite: "color: white;",
	FgYellow: "color: yellow;",
	Hidden: "visibility: hidden;",
	Reset: "color: inherit; background-color: inherit;",
	Reverse: "background-color: inherit; color: inherit;",
	Underscore: "text-decoration: underline;"
} as const;
export const TerminalColors = {
	BgBlack: "\x1b[40m",
	BgBlue: "\x1b[44m",
	BgCyan: "\x1b[46m",
	BgGreen: "\x1b[42m",
	BgMagenta: "\x1b[45m",
	BgRed: "\x1b[41m",
	BgWhite: "\x1b[47m",
	BgYellow: "\x1b[43m",
	Blink: "\x1b[5m",
	Bright: "\x1b[1m",
	Dim: "\x1b[2m",
	FgBlack: "\x1b[30m",
	FgBlue: "\x1b[34m",
	FgCyan: "\x1b[36m",
	FgGreen: "\x1b[32m",
	FgMagenta: "\x1b[35m",
	FgRed: "\x1b[31m",
	FgWhite: "\x1b[37m",
	FgYellow: "\x1b[33m",
	Hidden: "\x1b[8m",
	Reset: "\x1b[0m",
	Reverse: "\x1b[7m",
	Underscore: "\x1b[4m"
} as const;
export type ColorType = "error" | "info" | "success" | "warning" | keyof typeof TerminalColors;
